server:
  port: 8086

spring:
  application:
    name: warranty-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:warranty_service_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379

auth:
  api:
    key: ${AUTH_API_KEY:INTER_SERVICE_KEY}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8082}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8083}
  order-service:
    url: ${ORDER_SERVICE_URL:http://order-service:8085}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always